version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
    labels:
      - ci
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
